In [9]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [20]:
# Importing the dataset
#pd.set_option('display.max_rows', None)
dataset = pd.read_csv('Churn_Modelling.csv')
# X values start at 3 because we don't care about row number, surname, etc.
X = dataset.iloc[:, 3:13].values
# y value is the final column (Exited {0,1})
y = dataset.iloc[:, 13].values

In [15]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [39]:
#The actual data we will be working with (independent variables)
df = pd.DataFrame(data=X, columns=["Credit Score", "Country", "Gender", "Age", "Tenure", "Balance", "# of Products", "Has Credit Card", "Is Active", "Salary"])
df.head()

Credit Score Country  Gender Age Tenure  Balance # of Products  \
0          619  France  Female  42      2        0             1   
1          608   Spain  Female  41      1  83807.9             1   
2          502  France  Female  42      8   159661             3   
3          699  France  Female  39      1        0             2   
4          850   Spain  Female  43      2   125511             1   

  Has Credit Card Is Active   Salary  
0               1         1   101349  
1               0         1   112543  
2               1         0   113932  
3               0         0  93826.6  
4               1         1  79084.1

In [35]:
# Output data, whether or not the customer left the bank. (Should be vertical).
y

array([1, 0, 1, ..., 1, 1, 0])

In [45]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
#Label encode the second column of X (Geography)
#Converts country strings into integers (i.e. France = 0, Spain = 1, Germany = 2)
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

labelencoder_X_2 = LabelEncoder()
#Label encode the third column of X (Gender)
#Converts gender strings into integers (i.e. Male = 0, Female = 1)
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
#One hot encode the geography where each category has its own column

In [46]:
#Create a dummy variable at column 1
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
#Remove the second column from X to prevent the dummy variable trap
X = X[:, 1:]

/Users/FrancescoMac/opt/anaconda3/envs/Sudoku/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/Users/FrancescoMac/opt/anaconda3/envs/Sudoku/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [60]:
#The actual data we will be working with (independent variables)
df = pd.DataFrame(data=X, columns=["Country Code 1", "Country Code 2", "Credit Score", "Gender", "Age", "Tenure", "Balance", "# of Products", "Has Credit Card", "Is Active", "Salary"])
pd.set_option('display.max_rows', 10)
df

Country Code 1  Country Code 2  Credit Score  Gender   Age  Tenure  \
0                0.0             0.0         619.0     0.0  42.0     2.0   
1                0.0             1.0         608.0     0.0  41.0     1.0   
2                0.0             0.0         502.0     0.0  42.0     8.0   
3                0.0             0.0         699.0     0.0  39.0     1.0   
4                0.0             1.0         850.0     0.0  43.0     2.0   
...              ...             ...           ...     ...   ...     ...   
9995             0.0             0.0         771.0     1.0  39.0     5.0   
9996             0.0             0.0         516.0     1.0  35.0    10.0   
9997             0.0             0.0         709.0     0.0  36.0     7.0   
9998             1.0             0.0         772.0     1.0  42.0     3.0   
9999             0.0             0.0         792.0     0.0  28.0     4.0   

        Balance  # of Products  Has Credit Card  Is Active     Salary  
0          0.00            1.0              1.0        1.0  101348.88  
1      83807.86            1.0              0.0        1.0  112542.58  
2     159660.80            3.0              1.0        0.0  113931.57  
3          0.00            2.0              0.0        0.0   93826.63  
4     125510.82            1.0              1.0        1.0   79084.10  
...         ...            ...              ...        ...        ...  
9995       0.00            2.0              1.0        0.0   96270.64  
9996   57369.61            1.0              1.0        1.0  101699.77  
9997       0.00            1.0              0.0        1.0   42085.58  
9998   75075.31            2.0              1.0        0.0   92888.52  
9999  130142.79            1.0              1.0        0.0   38190.78  

[10000 rows x 11 columns]

In [61]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense


Using TensorFlow backend.


In [177]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 8, kernel_initializer = 'RandomNormal', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 8, kernel_initializer = 'RandomNormal', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'RandomNormal', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 50, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 2s 242us/step - loss: 0.6135 - accuracy: 0.7922
Epoch 2/100
8000/8000 [==============================] - 1s 71us/step - loss: 0.4465 - accuracy: 0.7965
Epoch 3/100
8000/8000 [==============================] - 1s 72us/step - loss: 0.4239 - accuracy: 0.8033
Epoch 4/100
8000/8000 [==============================] - 1s 70us/step - loss: 0.4090 - accuracy: 0.8111
Epoch 5/100
8000/8000 [==============================] - 1s 71us/step - loss: 0.3957 - accuracy: 0.8156
Epoch 6/100
8000/8000 [==============================] - 1s 72us/step - loss: 0.3827 - accuracy: 0.8344
Epoch 7/100
8000/8000 [==============================] - 1s 70us/step - loss: 0.3712 - accuracy: 0.8455
Epoch 8/100
8000/8000 [==============================] - 1s 70us/step - loss: 0.3626 - accuracy: 0.8528
Epoch 9/100
8000/8000 [==============================] - 1s 71us/step - loss: 0.3561 - accuracy: 0.8558
Epoch 10/100
8000/8000 [==============================] - 1s 70

8000/8000 [==============================] - 1s 70us/step - loss: 0.3313 - accuracy: 0.8650
Epoch 80/100
8000/8000 [==============================] - 1s 70us/step - loss: 0.3316 - accuracy: 0.8630
Epoch 81/100
8000/8000 [==============================] - 1s 69us/step - loss: 0.3310 - accuracy: 0.8635
Epoch 82/100
8000/8000 [==============================] - 1s 68us/step - loss: 0.3313 - accuracy: 0.8629
Epoch 83/100
8000/8000 [==============================] - 1s 68us/step - loss: 0.3312 - accuracy: 0.8648
Epoch 84/100
8000/8000 [==============================] - 1s 70us/step - loss: 0.3314 - accuracy: 0.8635
Epoch 85/100
8000/8000 [==============================] - 1s 70us/step - loss: 0.3313 - accuracy: 0.8639
Epoch 86/100
8000/8000 [==============================] - 1s 69us/step - loss: 0.3310 - accuracy: 0.8633
Epoch 87/100
8000/8000 [==============================] - 1s 70us/step - loss: 0.3313 - accuracy: 0.8631
Epoch 88/100
8000/8000 [==============================] - 1s 69us/st

In [169]:
# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [170]:
df = pd.DataFrame(data=y_pred)
pd.set_option('display.max_rows', 10)
df

0
0     0.160088
1     0.350664
2     0.121356
3     0.067417
4     0.048694
...        ...
1995  0.006786
1996  0.030143
1997  0.389547
1998  0.094717
1999  0.200120

[2000 rows x 1 columns]

In [171]:
# Converts array into True or False based on the threshold value
y_pred = (y_pred > 0.5)
df = pd.DataFrame(data=y_pred)
pd.set_option('display.max_rows', 10)
df

0
0     False
1     False
2     False
3     False
4     False
...     ...
1995  False
1996  False
1997  False
1998  False
1999  False

[2000 rows x 1 columns]

In [172]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1530,   65],
       [ 209,  196]])

In [173]:
acc = (cm[0][0] + cm[1][1]) / 2000
print("Accuracy: "),
acc

Accuracy: 


0.863

In [133]:
print("This accuracy is aligned with the ANN model, thus validating it!")

This accuracy is aligned with the ANN model, thus validating it!
